server:
  port: 8080

spring:
  application:
    name: api-gateway-ms
  cloud:
    gateway:
      routes:
      - id: auth-ms
        uri: lb://AUTH-MS
        predicates:
        - Path=/auth-ms/**

