app:
  service-registry:
    username: ${SERVICE_REGISTRY_USERNAME}
    password: ${SERVICE_REGISTRY_PASSWORD}
  auth:
    senha-jwt: vvi9ed9)^_65$_@!8xrh7@h@x_(n#aes!ms^)=3ps92^l5m3#w_msl-^3e(yd6d_b4=mrg7&gl=na!%brhod*jcnuvlz=2v9s@4r
    expiracao-jwt-minutos: 30
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: 'http://${app.service-registry.username}:${app.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

