app:
  service-registry:
    username: ${SERVICE_REGISTRY_USERNAME}
    password: ${SERVICE_REGISTRY_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: 'http://${app.service-registry.username}:${app.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

