server:
  port: 9001
  servlet:
    context-path: '/auth-ms/'

spring:
  application:
    name: auth-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-ms
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc: 
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    io.github.gleysongomes.auth: DEBUG
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

auth:
  broker:
    exchange:
      usuario-event: auth.usuario.event

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

app:
  auth:
    key-alias: auth-jwt
    key-store: classpath:auth-jwt.jks
    key-store-password: 'nM+kKdANhR4/tyANYHUYmjdho+ZjpvBnVgYvQTZtr9CTrgBdidl5Fnj8OCL6cbxurFUiPPiwpLnNHEmOOQikQA=='
    key-password: '1SVBeQ4F0KZMPS1nNa+0cmpds4eL7sUiJcWYT1OSewqi4Z9q7X1UDmntAQfxO2ROTOv6OPPVBddu5Qt21BBcNA=='

